import { Header } from '@/components/layout/Header'
import { TabNav } from '@/components/layout/TabNav'
import { Card } from '@/components/ui/Card'
import { AnalisisForm } from '@/components/analisis/AnalisisForm'
import { HasilAnalisis } from '@/components/analisis/HasilAnalisis'
import { PromptBox } from '@/components/analisis/PromptBox'
import { KalkulatorKomisi } from '@/components/komisi/KalkulatorKomisi'
import { MultiProduk } from '@/components/komisi/MultiProduk'
import { GeneratorKonten } from '@/components/konten/GeneratorKonten'
import { TemplateHashtag } from '@/components/konten/TemplateHashtag'
import { TrackingOverview } from '@/components/tracking/TrackingOverview'
export default function Dashboard({ searchParams }: { searchParams: { tab?: string } }) { const tab = searchParams.tab || 'analisis'; return <main className="mx-auto max-w-6xl px-4 py-6"><Header /><TabNav active={tab} /><div className="grid gap-5">{tab === 'analisis' && <><Card title="Analisis Produk"><AnalisisForm /></Card><Card title="Hasil Analisis"><HasilAnalisis /></Card><Card title="Prompt AI"><PromptBox /></Card></>}{tab === 'komisi' && <><Card title="Kalkulator Komisi"><KalkulatorKomisi /></Card><Card title="Multi Produk"><MultiProduk /></Card></>}{tab === 'konten' && <><Card title="Generator Konten AI"><GeneratorKonten /></Card><Card title="Template Hashtag"><TemplateHashtag /></Card></>}{tab === 'tracking' && <TrackingOverview />}</div></main> }
